services:
  - type: web
    name: 21ktools
    env: python
    plan: free  # Change if using a paid plan
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn tools21k.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "your_database_url_here"
